version: '3.9'

services:
  delivery:
    build:
      context: .
      dockerfile: delivery_service/Dockerfile
    ports:
      - "8000:80"
    depends_on:
      - payment
    environment:
      - DATABASE_URL=sqlite:///./test.db

  payment:
    build:
      context: .
      dockerfile: payment_service/Dockerfile
    ports:
      - "8001:80"
    environment:
      - DATABASE_URL=sqlite:///./payment.db